export const initialUsers = [
  {
    id: 1,
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@example.com',
    role: 'Lead Frontend Dev',
    department: 'Engineering',
    status: 'Active',
    location: 'San Francisco, CA',
    bio: 'Specialized in React, TypeScript, and design systems.',
  },
  {
    id: 2,
    name: 'Marcus Chen',
    email: 'marcus.chen@example.com',
    role: 'Backend Architect',
    department: 'Engineering',
    status: 'Active',
    location: 'Seattle, WA',
    bio: 'Focuses on distributed microservices, Spring Boot, and PostgreSQL.',
  },
  {
    id: 3,
    name: 'Elena Rostova',
    email: 'elena.rostova@example.com',
    role: 'Product Designer',
    department: 'Design',
    status: 'Pending',
    location: 'New York, NY',
    bio: 'User research, design tokens, and rapid Figma prototyping.',
  },
  {
    id: 4,
    name: 'Liam Patel',
    email: 'liam.patel@example.com',
    role: 'Product Manager',
    department: 'Product',
    status: 'Inactive',
    location: 'Austin, TX',
    bio: 'Product roadmapping and customer feedback analytics.',
  },
  {
    id: 5,
    name: 'Zoe Vance',
    email: 'zoe.vance@example.com',
    role: 'DevOps Engineer',
    department: 'Infrastructure',
    status: 'Active',
    location: 'Chicago, IL',
    bio: 'Kubernetes clusters, CI/CD pipelines, and cloud automation.',
  },
];
